[package]
name = "howmanysmall/table-utilities" # TODO: Convert to bura-games organization.
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Utilities related to tables."
license = "MIT"
exclude = [
	".gitignore",
	".luaurc",
	".vscode",
	"build",
	"docs",
	"moonwave.toml",
	"rokit.toml",
	"selene.toml",
	"sourcemap.json",
	"stylua.toml",
	"TableUtilities.code-workspace",
	"testez-companion.toml",
	"testez.yml",
]

[dependencies]
